<?php

namespace CnabPHP\resources\B133\remessa\cnab240;

use CnabPHP\resources\generico\remessa\cnab240\Generico0;

class Registro0 extends Generico0
{
    protected $meta = array(
        'codigo_banco' => array(
            'tamanho' => 3,
            'default' => '133',
            'tipo' => 'int',
            'required' => true),
        'codigo_lote' => array(
            'tamanho' => 4,
            'default' => '0000',
            'tipo' => 'int',
            'required' => true),
        'tipo_registro' => array(
            'tamanho' => 1,
            'default' => '0',
            'tipo' => 'int',
            'required' => true),
        'filler1' => array(
            'tamanho' => 9,
            'default' => ' ',
            'tipo' => 'alfa',
            'required' => true),
        'tipo_inscricao' => array(
            'tamanho' => 1,
            'default' => '0',
            'tipo' => 'int',
            'required' => true),
        'numero_inscricao' => array(
            'tamanho' => 14,
            'default' => '0',
            'tipo' => 'int',
            'required' => true),
        'uso_bb1' => array(
            'tamanho' => 20,
            'default' => ' ',
            'tipo' => 'alfa',
            'required' => true),
        'agencia' => array(
            'tamanho' => 5,
            'default' => '0',
            'tipo' => 'int',
            'required' => true),
        'agencia_dv' => array(
            'tamanho' => 1,
            'default' => '',
            'tipo' => 'alfa',
            'required' => true),
        'conta' => array(
            'tamanho' => 12,
            'default' => '0',
            'tipo' => 'int',
            'required' => true),
        'conta_dv' => array(
            'tamanho' => 1,
            'default' => '0',
            'tipo' => 'alfa',
            'required' => true),
        'filler2' => array(
            'tamanho' => 1,
            'default' => ' ',
            'tipo' => 'alfa',
            'required' => true),
        'nome_empresa' => array(
            'tamanho' => 30,
            'default' => '',
            'tipo' => 'alfa',
            'required' => true),
        'nome_banco' => array(
            'tamanho' => 30,
            'default' => 'CRESOL CONFEDERACAO',
            'tipo' => 'alfa',
            'required' => true),
        'filler3' => array(
            'tamanho' => 10,
            'default' => ' ',
            'tipo' => 'alfa',
            'required' => true),
        'codigo_remessa' => array(
            'tamanho' => 1,
            'default' => '1',
            'tipo' => 'int',
            'required' => true),
        'data_geracao' => array(
            'tamanho' => 8,
            'default' => '',
            'tipo' => 'date',
            'required' => true),
        'hora_geracao' => array(
            'tamanho' => 6,
            'default' => '',
            'tipo' => 'int',
            'required' => true),
        'numero_sequencial_arquivo' => array(
            'tamanho' => 6,
            'default' => '0',
            'tipo' => 'int',
            'required' => true),
        'versao_layout' => array(
            'tamanho' => 3,
            'default' => '084',
            'tipo' => 'int',
            'required' => true),
        'densidade_gravacao' => array(
            'tamanho' => 5,
            'default' => '0',
            'tipo' => 'int',
            'required' => true),
        'filler4' => array(
            'tamanho' => 20,
            'default' => ' ',
            'tipo' => 'alfa',
            'required' => true),
        'situacao_arquivo2' => array(
            'tamanho' => 20,
            'default' => ' ',
            'tipo' => 'alfa',
            'required' => true),
        'filler5' => array(
            'tamanho' => 14,
            'default' => ' ',
            'tipo' => 'alfa',
            'required' => true),
        'filler6' => array(
            'tamanho' => 3,
            'default' => '000',
            'tipo' => 'alfa',
            'required' => true),
        'filler7' => array(
            'tamanho' => 12,
            'default' => ' ',
            'tipo' => 'alfa',
            'required' => true)
    );
}
