<?php

namespace CnabPHP\resources\B133\retorno\L084;

use CnabPHP\resources\generico\retorno\L084\Generico3;

class Registro3U extends Generico3
{
    protected $meta = array(
        'codigo_banco' => array(
            'tamanho' => 3,
            'default' => '133',
            'tipo' => 'int',
            'required' => true),
        'codigo_lote' => array(
            'tamanho' => 4,
            'default' => 1,
            'tipo' => 'int',
            'required' => true),
        'tipo_registro' => array(
            'tamanho' => 1,
            'default' => '3',
            'tipo' => 'int',
            'required' => true),
        'numero_registro' => array(
            'tamanho' => 5,
            'default' => '0',
            'tipo' => 'int',
            'required' => true),
        'seguimento' => array(
            'tamanho' => 1,
            'default' => 'U',
            'tipo' => 'alfa',
            'required' => true),
        'filler1' => array(
            'tamanho' => 1,
            'default' => ' ',
            'tipo' => 'int',
            'required' => true),
        'codigo_movimento' => array(
            'tamanho' => 2,
            'default' => '',
            'tipo' => 'int',
            'required' => true),
        'vlr_juros_mora' => array(
            'tamanho' => 13,
            'default' => '',
            'tipo' => 'decimal',
            'precision' => 2,
            'required' => true),
        'vlr_desconto' => array(
            'tamanho' => 13,
            'default' => '',
            'tipo' => 'decimal',
            'precision' => 2,
            'required' => true),
        'vlr_abatimento' => array(
            'tamanho' => 13,
            'default' => '',
            'tipo' => 'decimal',
            'precision' => 2,
            'required' => true),
        'vlr_IOF' => array(
            'tamanho' => 13,
            'default' => '',
            'tipo' => 'decimal',
            'precision' => 2,
            'required' => true),
        'vlr_pago' => array(
            'tamanho' => 13,
            'default' => '',
            'tipo' => 'decimal',
            'precision' => 2,
            'required' => true),
        'vlr_liquido' => array(
            'tamanho' => 13,
            'default' => '',
            'tipo' => 'decimal',
            'precision' => 2,
            'required' => true),
        'vlr_outras_despesas' => array(
            'tamanho' => 13,
            'default' => ' ',
            'tipo' => 'decimal',
            'precision' => 2,
            'required' => true),
        'vlr_outros_creditos' => array(
            'tamanho' => 13,
            'default' => '',
            'tipo' => 'decimal',
            'precision' => 2,
            'required' => true),
        'data_ocorrencia' => array(
            'tamanho' => 8,
            'default' => '',
            'tipo' => 'date',
            'required' => true),
        'data_credito' => array(
            'tamanho' => 8,
            'default' => '',
            'tipo' => 'date',
            'required' => false),
        'filler2' => array(
            'tamanho' => 4,
            'default' => '',
            'tipo' => 'int',
            'required' => true),
        'data_ocorrencia2' => array(
            'tamanho' => 8,
            'default' => '',
            'tipo' => 'date',
            'required' => false),
        'vlr_ocorrencia' => array(
            'tamanho' => 13,
            'default' => '',
            'tipo' => 'decimal',
            'precision' => 2,
            'required' => true),
        'complem_ocorrencia' => array(
            'tamanho' => 30,
            'default' => ' ',
            'tipo' => 'alfa',
            'required' => true),
        'codigo_banco_correspondente' => array(
            'tamanho' => 3,
            'default' => '',
            'tipo' => 'int',
            'required' => true),
        'nosso_numero' => array(
            'tamanho' => 20,
            'default' => '',
            'tipo' => 'int',
            'required' => true),
        'filler3' => array(
            'tamanho' => 7,
            'default' => ' ',
            'tipo' => 'alfa',
            'required' => true),
    );
}
